__default__:
  memory: 5000
  n: 1
  name: "{rule}.{wildcards}"
  queue: "standard"
  outfile: "{log}"
# 01_pre-processing.smk
copy_videos:
  queue: datamover
# 02_tracking.smk
track_videos:
  memory: "{resources.mem_mb}"
coloured_trails:
  memory: "{resources.mem_mb}"
trajectories_to_csv:
  memory: "{resources.mem_mb}"
# 03_qc.smk
assign_ref_test:
  memory: "{resources.mem_mb}"
tracking_success:
  memory: "{resources.mem_mb}"  