__default__:
  memory: 5000
  n: 1
  name: "{rule}.{wildcards}"
  queue: "standard"
  outfile: "{log}"
# 01_pre-processing.smk
copy_videos:
  queue: datamover
# 02_tracking.smk
track_videos:
  memory: "{resources.mem_mb}"
  #queue: "bigmem"