####################
# Config files
####################
raw_metadata:
    config/20220509_New_Fish_Movies.xlsx
samples_long:
    config/samples_long.csv
samples_file:
    config/samples.csv
excluded_videos:
    config/excluded_videos.csv
####################
# Parameters
####################
seconds_interval:
    - 0.05
    - 0.08
    - 0.1
    - 0.15
    - 0.2
    - 0.3
    - 0.5
    - 1
####################
# Locations
####################
repo_dir:
    /hps/software/users/birney/ian/repos/MIKK_F2_tracking
raw_data_dir:
    /nfs/ftp/private/indigene_ftp/upload/behaviour/transfer/F2/all_F2
working_dir:
    /hps/nobackup/birney/users/ian/MIKK_F2_tracking
data_store_dir:
    /nfs/research/birney/users/ian/MIKK_F2_tracking
shared_dir:
    /hps/nobackup/birney/users/ian/MIKK_all
####################
# Containers
####################
#ffmpeg:
#    docker://jrottenberg/ffmpeg:4.4-ubuntu
opencv:
    /hps/nobackup/birney/users/ian/containers/MIKK_F0_tracking/opencv_4.5.1.sif
idtrackerai:
    # NOTE: Dockerfile for this container: workflow/envs/idtrackerai/Dockerfile
    docker://saulpierottiebi/idtrackerai_cpu_gui:latest
rocker_tidyverse:
    docker://rocker/tidyverse:4.1.2
R_4.1.2:
    # NOTE: singularity definition file for this container: workflow/envs/R_4.1.2.def
    /hps/nobackup/birney/users/ian/containers/MIKK_F2_tracking/R_4.1.2.sif



